import {
  appendTransactionMessageInstructions,
  compileTransaction,
  createSolanaRpc,
  createTransactionMessage,
  decompileTransactionMessage,
  generateKeyPairSigner,
  getBase64Encoder,
  getBase64EncodedWireTransaction,
  getCompiledTransactionMessageDecoder,
  getSignatureFromTransaction,
  getTransactionDecoder,
  getTransactionEncoder,
  getTransactionMessageComputeUnitLimit,
  getTransactionMessageComputeUnitPrice,
  pipe,
  setTransactionMessageComputeUnitLimit,
  setTransactionMessageComputeUnitPrice,
  setTransactionMessageFeePayerSigner,
  setTransactionMessageLifetimeUsingBlockhash,
  signTransactionMessageWithSigners,
  type Instruction,
  type TransactionSigner,
} from "@solana/kit";
import {
  getAddMemoInstruction,
  MEMO_PROGRAM_ADDRESS,
} from "@solana-program/memo";
import { SYSTEM_PROGRAM_ADDRESS } from "@solana-program/system";
import { ClientProvider } from "@solana/react";
import { Surfnet } from "@solana/surfpool";
import { act, cleanup, renderHook, waitFor } from "@testing-library/react";
import {
  afterAll,
  afterEach,
  beforeAll,
  beforeEach,
  expect,
  test,
  vi,
} from "vitest";
import { StrictMode, type ReactNode } from "react";
import {
  EVENT_ID,
  EVENT_REFERENCE,
  MAX_MEMO_BYTES,
  buildCheckInInstructions,
  encodeCheckInMemo,
  parseCheckInTransaction,
  readCheckInFeed,
  readConfirmedCheckIn,
  simulateCheckIn,
} from "../app/lib/check-in";
import { useCheckIn } from "../app/lib/hooks/use-check-in";
import { createAppClient } from "../app/lib/solana-client";
import {
  mockWallet,
  mockWalletAddress,
  registerMockWallet,
  resetMockWallet,
} from "./mock-wallet";

let surfnet: Surfnet;
let rpc: ReturnType<typeof createSolanaRpc>;

// Kit RPC methods are generated by a Proxy rather than own properties.
function overrideRpcMethods(
  overrides: Partial<Record<keyof typeof rpc, unknown>>
) {
  return new Proxy(rpc, {
    get(target, property, receiver) {
      return Object.hasOwn(overrides, property)
        ? Reflect.get(overrides, property)
        : Reflect.get(target, property, receiver);
    },
  });
}

function decodeWalletMessage(wireBytes: Uint8Array) {
  const transaction = getTransactionDecoder().decode(wireBytes);
  const compiled = getCompiledTransactionMessageDecoder().decode(
    transaction.messageBytes
  );
  if (compiled.version !== 0) throw new Error("Expected a v0 transaction");
  return decompileTransactionMessage(compiled, {
    lastValidBlockHeight: 0n,
  });
}

// Model Phantom's documented auto-fee conditions at the wallet boundary:
// unsigned, no existing compute-budget settings, and still below 1232 bytes.
function applyPhantomPriorityFees(wireBytes: Uint8Array) {
  const transaction = getTransactionDecoder().decode(wireBytes);
  const message = decodeWalletMessage(wireBytes);
  if (
    Object.values(transaction.signatures).some((value) => value !== null) ||
    getTransactionMessageComputeUnitLimit(message) !== undefined ||
    getTransactionMessageComputeUnitPrice(message) !== undefined
  ) {
    return wireBytes;
  }
  const enhanced = pipe(
    message,
    (m) => setTransactionMessageComputeUnitLimit(50_000, m),
    (m) => setTransactionMessageComputeUnitPrice(1_000n, m),
    compileTransaction,
    (transaction) => new Uint8Array(getTransactionEncoder().encode(transaction))
  );
  return enhanced.length < 1232 ? enhanced : wireBytes;
}

beforeAll(() => {
  surfnet = Surfnet.start();
  rpc = createSolanaRpc(surfnet.rpcUrl);
  registerMockWallet();
}, 60_000);

beforeEach(() => {
  localStorage.clear();
  resetMockWallet();
});

afterEach(() => {
  cleanup();
  vi.restoreAllMocks();
});

afterAll(() => surfnet?.stop());

async function sendInstructions(
  signer: TransactionSigner,
  instructions: readonly Instruction[]
) {
  const { value: blockhash } = await rpc.getLatestBlockhash().send();
  const message = pipe(
    createTransactionMessage({ version: 0 }),
    (m) => setTransactionMessageFeePayerSigner(signer, m),
    (m) => setTransactionMessageLifetimeUsingBlockhash(blockhash, m),
    (m) => appendTransactionMessageInstructions(instructions, m)
  );
  const signed = await signTransactionMessageWithSigners(message);
  await rpc
    .sendTransaction(getBase64EncodedWireTransaction(signed), {
      encoding: "base64",
      skipPreflight: false,
    })
    .send();
  return getSignatureFromTransaction(signed);
}

test("a real zero SOL self-transfer and memo are indexed by the unfunded event reference", async () => {
  const signer = await generateKeyPairSigner();
  surfnet.fundSol(signer.address, 2_000_000_000);
  const { value: before } = await rpc.getBalance(signer.address).send();
  const { value: referenceBefore } = await rpc
    .getBalance(EVENT_REFERENCE)
    .send();
  expect(referenceBefore).toBe(0n);
  const prepared = await simulateCheckIn(
    rpc,
    signer,
    "成都同学",
    "今天一起做 Solana demo。"
  );
  // Simulation uses zero signatures and cannot move funds or create a record.
  expect(
    Object.values(prepared.transaction.signatures).every(
      (signature) => signature === null
    )
  ).toBe(true);
  expect(
    getTransactionMessageComputeUnitPrice(prepared.transactionMessage)
  ).toBe(0n);
  expect(
    getTransactionMessageComputeUnitLimit(prepared.transactionMessage)
  ).toBeGreaterThan(Number(prepared.computeUnits));
  expect((await rpc.getBalance(signer.address).send()).value).toBe(before);
  const signed = await signTransactionMessageWithSigners(
    prepared.transactionMessage
  );
  const txSignature = getSignatureFromTransaction(signed);
  await rpc
    .sendTransaction(getBase64EncodedWireTransaction(signed), {
      encoding: "base64",
    })
    .send();
  let entry: Awaited<ReturnType<typeof readConfirmedCheckIn>> = null;
  await waitFor(async () => {
    entry = await readConfirmedCheckIn(rpc, txSignature);
    expect(entry).not.toBeNull();
  });
  expect(entry).toMatchObject({
    wallet: signer.address,
    nickname: "成都同学",
    message: "今天一起做 Solana demo。",
    signature: txSignature,
  });
  const signatures = await rpc.getSignaturesForAddress(EVENT_REFERENCE).send();
  expect(signatures.some((item) => item.signature === txSignature)).toBe(true);
  const feed = await readCheckInFeed(rpc);
  expect(feed.entries.some((item) => item.signature === txSignature)).toBe(
    true
  );
  const transaction = await rpc
    .getTransaction(txSignature, {
      encoding: "jsonParsed",
      commitment: "confirmed",
      maxSupportedTransactionVersion: 0,
    })
    .send();
  const after = (await rpc.getBalance(signer.address).send()).value;
  // No recipient receives SOL; the sole balance reduction is the real network fee.
  expect(before - after).toBe(transaction?.meta?.fee);
  expect((await rpc.getBalance(EVENT_REFERENCE).send()).value).toBe(
    referenceBefore
  );
});

test("an actual on-chain transaction for another event is excluded from this wall", async () => {
  const signer = await generateKeyPairSigner();
  surfnet.fundSol(signer.address, 1_000_000_000);
  const instructions = buildCheckInInstructions(
    signer,
    "别的活动",
    "不要进入成都墙"
  );
  const data = JSON.parse(encodeCheckInMemo("别的活动", "不要进入成都墙"));
  data.event = "another-event";
  const otherMemo = getAddMemoInstruction({
    memo: JSON.stringify(data),
    signers: [signer],
  });
  const txSignature = await sendInstructions(signer, [
    otherMemo,
    instructions[1],
  ]);
  const transaction = await rpc
    .getTransaction(txSignature, {
      encoding: "jsonParsed",
      maxSupportedTransactionVersion: 0,
    })
    .send();
  expect(transaction?.meta?.err).toBeNull();
  expect(parseCheckInTransaction(transaction, txSignature)).toBeNull();
  expect(
    (await readCheckInFeed(rpc)).entries.some(
      (entry) => entry.signature === txSignature
    )
  ).toBe(false);
});

test("simulation rejects a wallet unable to pay the fee without signing it", async () => {
  const signer = await generateKeyPairSigner();
  await expect(
    simulateCheckIn(rpc, signer, "未领币", "模拟必须失败")
  ).rejects.toThrow();
  expect((await rpc.getBalance(signer.address).send()).value).toBe(0n);
});

test("a Phantom-like wallet keeps the reviewed message and confirms only after explicit approval", async () => {
  surfnet.fundSol(mockWalletAddress, 2_000_000_000);
  const client = createAppClient("localnet", {
    rpcUrl: surfnet.rpcUrl,
    rpcSubscriptionsUrl: surfnet.wsUrl,
  });
  await waitFor(() =>
    expect(
      client.wallet
        .getState()
        .wallets.some((wallet) => wallet.name === "Mock Wallet")
    ).toBe(true)
  );
  const discovered = client.wallet
    .getState()
    .wallets.find((wallet) => wallet.name === "Mock Wallet")!;
  await client.wallet.connect(discovered);
  const originalSign =
    mockWallet.features["solana:signTransaction"].signTransaction;
  const sign = vi.spyOn(
    mockWallet.features["solana:signTransaction"],
    "signTransaction"
  );
  sign.mockImplementation(
    async (...inputs: readonly { transaction: Uint8Array }[]) =>
      originalSign(
        ...inputs.map(({ transaction }) => {
          const walletTransaction = applyPhantomPriorityFees(transaction);
          expect(walletTransaction).toEqual(transaction);
          return { transaction: walletTransaction };
        })
      )
  );
  const wrapper = ({ children }: { children: ReactNode }) => (
    <StrictMode>
      <ClientProvider client={client}>{children}</ClientProvider>
    </StrictMode>
  );
  const { result } = renderHook(() => useCheckIn(), { wrapper });
  await waitFor(() => expect(result.current.isLoading).toBe(false));
  expect(result.current.feedError).toBeNull();
  await act(async () => {
    await result.current.confirm();
  });
  expect(sign).not.toHaveBeenCalled();
  await act(async () => {
    await result.current.prepare("钱包同学", "先模拟，再亲自签名");
  });
  expect(result.current.status).toBe("ready");
  expect(result.current.simulationSummary).toContain("转账 0 SOL");
  expect(sign).not.toHaveBeenCalled();
  await act(async () => {
    await result.current.confirm();
  });
  expect(sign).toHaveBeenCalledTimes(1);
  expect(result.current.status).toBe("success");
  expect(result.current.lastSignature).not.toBeNull();
  expect(
    result.current.entries.some(
      (entry) => entry.signature === result.current.lastSignature
    )
  ).toBe(true);
  await act(async () => {
    await result.current.prepare("下一笔", "钱包拒绝签名");
  });
  expect(result.current.lastSignature).toBeNull();
  sign.mockRejectedValueOnce(new Error("User rejected signing"));
  await act(async () => {
    await result.current.confirm();
  });
  expect(result.current.status).toBe("error");
  expect(result.current.transactionError).toContain("取消了钱包签名");
  expect(result.current.lastSignature).toBeNull();
});

test("the old unsigned memo would be enhanced by Phantom, but the prepared message has explicit budgets", async () => {
  const signer = await generateKeyPairSigner();
  surfnet.fundSol(signer.address, 1_000_000_000);
  const { value: lifetime } = await rpc.getLatestBlockhash().send();
  const oldMessage = pipe(
    createTransactionMessage({ version: 0 }),
    (m) => setTransactionMessageFeePayerSigner(signer, m),
    (m) => setTransactionMessageLifetimeUsingBlockhash(lifetime, m),
    (m) =>
      appendTransactionMessageInstructions(
        buildCheckInInstructions(signer, "钱包兼容", "明确预算再签名"),
        m
      )
  );
  const oldBytes = new Uint8Array(
    getTransactionEncoder().encode(compileTransaction(oldMessage))
  );
  expect(applyPhantomPriorityFees(oldBytes)).not.toEqual(oldBytes);
  const prepared = await simulateCheckIn(
    rpc,
    signer,
    "钱包兼容",
    "明确预算再签名"
  );
  const newBytes = new Uint8Array(
    getTransactionEncoder().encode(prepared.transaction)
  );
  expect(applyPhantomPriorityFees(newBytes)).toEqual(newBytes);
  expect(
    getTransactionMessageComputeUnitPrice(prepared.transactionMessage)
  ).toBe(0n);
});

test("an unreported CU estimate prevents preparing a wallet transaction instead of guessing a budget", async () => {
  const signer = await generateKeyPairSigner();
  surfnet.fundSol(signer.address, 1_000_000_000);
  const originalSimulate = rpc.simulateTransaction;
  const simulate = vi.fn(
    (...args: Parameters<typeof rpc.simulateTransaction>) => {
      const pending = originalSimulate(...args);
      return {
        ...pending,
        send: async (...options: Parameters<typeof pending.send>) => {
          const result = await pending.send(...options);
          return {
            ...result,
            value: { ...result.value, unitsConsumed: undefined },
          };
        },
      };
    }
  );
  const incompleteRpc = overrideRpcMethods({ simulateTransaction: simulate });
  await expect(
    simulateCheckIn(incompleteRpc, signer, "缺少估计", "需要正常的节点数据")
  ).rejects.toThrow("无法估计本次交易所需的计算预算");
  expect(simulate).toHaveBeenCalledTimes(1);
});

test("the finalized budgeted message is simulated again and its exact message determines the fee", async () => {
  const signer = await generateKeyPairSigner();
  surfnet.fundSol(signer.address, 1_000_000_000);
  const simulate = vi.fn(rpc.simulateTransaction);
  const fee = vi.fn(rpc.getFeeForMessage);
  const observedRpc = overrideRpcMethods({
    simulateTransaction: simulate,
    getFeeForMessage: fee,
  });
  const prepared = await simulateCheckIn(
    observedRpc,
    signer,
    "预算审核",
    "只签最终模拟的内容"
  );
  expect(simulate).toHaveBeenCalledTimes(2);
  expect(simulate.mock.calls[1][0]).toBe(
    getBase64EncodedWireTransaction(prepared.transaction)
  );
  const probe = decodeWalletMessage(
    new Uint8Array(getBase64Encoder().encode(simulate.mock.calls[0][0]))
  );
  expect(getTransactionMessageComputeUnitLimit(probe)).toBe(1_400_000);
  expect(getTransactionMessageComputeUnitPrice(probe)).toBe(0n);
  expect(fee).toHaveBeenCalledTimes(1);
  const feeMessageBytes = getBase64Encoder().encode(fee.mock.calls[0][0]);
  expect(feeMessageBytes).toEqual(prepared.transaction.messageBytes);
});

test("a wallet that changes the reviewed budget is still blocked before any broadcast", async () => {
  surfnet.fundSol(mockWalletAddress, 2_000_000_000);
  const requests = vi.spyOn(globalThis, "fetch");
  const client = createAppClient("localnet", {
    rpcUrl: surfnet.rpcUrl,
    rpcSubscriptionsUrl: surfnet.wsUrl,
  });
  await waitFor(() =>
    expect(
      client.wallet
        .getState()
        .wallets.some((wallet) => wallet.name === "Mock Wallet")
    ).toBe(true)
  );
  const discovered = client.wallet
    .getState()
    .wallets.find((wallet) => wallet.name === "Mock Wallet")!;
  await client.wallet.connect(discovered);
  const originalSign =
    mockWallet.features["solana:signTransaction"].signTransaction;
  const sign = vi.spyOn(
    mockWallet.features["solana:signTransaction"],
    "signTransaction"
  );
  sign.mockImplementation(
    async (...inputs: readonly { transaction: Uint8Array }[]) =>
      originalSign(
        ...inputs.map(({ transaction }) => ({
          transaction: new Uint8Array(
            getTransactionEncoder().encode(
              compileTransaction(
                setTransactionMessageComputeUnitPrice(
                  1n,
                  decodeWalletMessage(transaction)
                )
              )
            )
          ),
        }))
      )
  );
  const wrapper = ({ children }: { children: ReactNode }) => (
    <ClientProvider client={client}>{children}</ClientProvider>
  );
  const { result } = renderHook(() => useCheckIn(), { wrapper });
  await act(async () => result.current.prepare("严格校验", "钱包不能更改费用"));
  expect(result.current.status).toBe("ready");
  await act(async () => result.current.confirm());
  expect(result.current.status).toBe("error");
  expect(result.current.transactionError).toContain(
    "钱包修改了已审核的交易内容"
  );
  expect(result.current.lastSignature).toBeNull();
  expect(sign).toHaveBeenCalledTimes(1);
  const requestMethods = requests.mock.calls.map(([, init]) =>
    typeof init?.body === "string" ? JSON.parse(init.body).method : null
  );
  expect(requestMethods).toContain("simulateTransaction");
  expect(requestMethods).not.toContain("sendTransaction");
});

function fixture(overrides: Record<string, unknown> = {}) {
  const wallet = mockWalletAddress;
  return {
    blockTime: 1_790_000_000,
    meta: { err: null },
    transaction: {
      message: {
        accountKeys: [
          { pubkey: wallet, signer: true, writable: true },
          { pubkey: EVENT_REFERENCE, signer: false, writable: false },
        ],
        instructions: [
          {
            programId: MEMO_PROGRAM_ADDRESS,
            parsed: encodeCheckInMemo("同学", "真实签名"),
          },
          {
            programId: SYSTEM_PROGRAM_ADDRESS,
            parsed: {
              type: "transfer",
              info: { source: wallet, destination: wallet, lamports: 0 },
            },
          },
        ],
      },
    },
    ...overrides,
  };
}

test("failed transactions and malformed data cannot become attendance records", () => {
  expect(parseCheckInTransaction(fixture(), "signature")).toMatchObject({
    wallet: mockWalletAddress,
    timestamp: 1_790_000_000,
  });
  expect(
    parseCheckInTransaction(
      fixture({ meta: { err: { InstructionError: [0, "Custom"] } } }),
      "signature"
    )
  ).toBeNull();
  expect(
    parseCheckInTransaction(fixture({ blockTime: null }), "signature")
  ).toBeNull();
  expect(parseCheckInTransaction({ transaction: {} }, "signature")).toBeNull();
  const wrongVersion = fixture();
  wrongVersion.transaction.message.instructions[0].parsed = JSON.stringify({
    app: "chengdu-check-in",
    event: EVENT_ID,
    v: 2,
    nickname: "同学",
    message: "不支持",
  });
  expect(parseCheckInTransaction(wrongVersion, "signature")).toBeNull();
  const missingReference = fixture();
  missingReference.transaction.message.accountKeys.pop();
  expect(parseCheckInTransaction(missingReference, "signature")).toBeNull();
});

test("the payload limit counts actual UTF-8 bytes, including Chinese and emoji", () => {
  const ascii = encodeCheckInMemo("同学", "a".repeat(100));
  expect(new TextEncoder().encode(ascii).length).toBeLessThanOrEqual(
    MAX_MEMO_BYTES
  );
  expect(() => encodeCheckInMemo("同学", "🧑‍💻".repeat(30))).toThrow(
    /UTF-8|字符/
  );
  expect(() => encodeCheckInMemo("成".repeat(24), "都".repeat(100))).toThrow(
    /UTF-8/
  );
  expect(() => encodeCheckInMemo("", "留言")).toThrow(/昵称/);
  expect(() => encodeCheckInMemo("同学", "")).toThrow(/留言/);
});
